### ISSUE TITLE
 部分苹果手机报错 The operation is insecure .

### ISSUE THREAD

**Issue by reboy** [lancer07/vue-qr-poster#1]
The operation is insecure .
解决办法：
var image = new Image();
//位置换一下下。
image.setAttribute("crossOrigin",'Anonymous');//跨域在前
image.src = href.href;//赋值在后

**Comment by lancer07** [comment]
fixed

**Comment by lancer07** [comment]
> The operation is insecure . 解决办法： var image = new Image(); //位置换一下下。 image.setAttribute("crossOrigin",'Anonymous');//跨域在前 image.src = href.href;//赋值在后

fixed
